[FIX] sale_order_type_automation: commit invoice creation and complet…
ingadhoc/sale pull request #1018
Opened 2024-11-06 15:31 UTC by augusto-weiss

…e rollback

2024-11-06 15:32 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/1018).

2024-11-06 18:09 UTC, zaoral commented on sale_order_type_automation/models/sale_order.py
> +            validate_using_try_except = bool(self._context.get("validate_using_try_except")) or rec.type_id.invoicing_atomation == 'try_validate_invoice'
```python
            if rec.type_id.invoicing_atomation in ['try_validate_invoice', 'validate_invoice']:
                if self._context.get("validate_using_try_except"):
                    rec.env.cr.commit()
                try:
                    invoices.sudo().action_post()
                except Exception as error:
                    rec.env.cr.rollback()
                    message = _(
                        "We couldn't validate the automatically created "
                        "invoices (ids %s), you will need to validate them"
                        " manually. This is what we get: %s") % (
                            invoices.ids, error)
                    invoices.message_post(body=message)
                    rec.message_post(body=message)
```

2024-11-06 18:15 UTC, zaoral commented on sale_order_type_automation/models/sale_order.py
> +            validate_using_try_except = bool(self._context.get("validate_using_try_except")) or rec.type_id.invoicing_atomation == 'try_validate_invoice'
raise_invoice_validation_error

2024-11-07 14:45 UTC, zaoral requested changes

2024-11-07 14:45 UTC, zaoral commented on sale_order_type_automation/models/sale_order.py
> +                        raise UserError(message)
```suggestion
                        raise error
```

2024-11-07 15:11 UTC, zaoral approved these changes

2024-11-07 15:11 UTC, zaoral commented
@roboadhoc r+

2024-11-07 15:27 UTC, closed without merging