[IMP] some improvement form 9.0 4bbaee23aea2f958ca29199aa97bb4bc46d5c381
ingadhoc/sale pull request #114
Opened 2018-06-08 14:51 UTC by nicomacr

2018-06-08 17:12 UTC, jjscarafia requested changes

2018-06-08 17:12 UTC, jjscarafia commented on portal_sale_distributor/views/product_product_views.xml
> +    <record id="product.tree" model="ir.ui.view">
Nico, fijate que runbot da mal por este id que estaría mal, sería tal vez "view_product_tree"

2018-06-08 18:35 UTC, nicomacr commented on portal_sale_distributor/views/product_product_views.xml
> +    <record id="product.tree" model="ir.ui.view">
Ahi lo corregi

2018-06-09 12:08 UTC, jjscarafia approved these changes

2018-06-09 12:31 UTC, merged