13.0 t 21976 nm
ingadhoc/sale pull request #341
Opened 2020-06-12 11:07 UTC by nmadhoc

2020-06-17 19:12 UTC, jjscarafia commented on sale_order_lot_selection_ux/models/sale_order_line.py
> +        # for rec in self.filtered(
borrar comentario

2020-06-17 19:14 UTC, jjscarafia requested changes

2020-06-17 19:14 UTC, jjscarafia commented on sale_order_lot_selection_ux/models/sale_order_line.py
> +                rec.available_lot_ids = available_lot_ids
agregar
else:
    rec.aviablel.. = rec.env['stock.production.lot']

2020-06-18 10:44 UTC, nmadhoc commented on sale_order_lot_selection_ux/models/sale_order_line.py
> +                rec.available_lot_ids = available_lot_ids
Ahora recuerdo bien porque no le puse un if else acá. 
Siguiendo el código y revisando con un trace, siempre le va a asignar una lista a ese campo. Puede ser una lista vacia [] o una lista con ids

2020-06-18 11:14 UTC, closed without merging

2020-06-18 11:15 UTC, nmadhoc commented
Quedó muy desorganizado y se incluyó por error otro módulo. Hago PR otra vez