[ADD] crm_stage_teams
ingadhoc/sale pull request #379
Opened 2020-11-03 17:22 UTC by nmadhoc

2020-11-05 08:56 UTC, jjscarafia requested changes
@nmadhoc ahí van un par de comentarios

2020-11-05 08:56 UTC, jjscarafia commented on crm_stage_teams/models/crm_lead.py
> +    stage_id = fields.Many2one('crm.stage', string='Stage', ondelete='restrict', track_visibility='onchange', index=True, copy=False,
este campo ya existe en crm.lead. hay alguna parte que haga falta modificar? porque si no no hace falta redefinirlo, o solo redefinir aquello que haya cambiado, imagino algo así
```
stage_id = fields.Many2one(group_expand='_read_group_stage_ids', domain="['|', ('team_ids', '=', False), ('team_ids', '=', team_id)]")
```

entiendo que debe cambiar solo eso respecto a la definición original del  método

2020-11-05 08:56 UTC, jjscarafia commented on crm_stage_teams/models/crm_lead.py
> +            search_domain = ['|', ('id', 'in', stages.ids), ('team_ids', '=', False)]
este else lo veo medio raro, cual sería la razón?
en el de helpdesk no lo veo y necesitamos algo igual que helpdesk
https://github.com/odoo/enterprise/blob/13.0/helpdesk/models/helpdesk_ticket.py#L176

2020-11-09 13:27 UTC, nmadhoc commented on crm_stage_teams/models/crm_lead.py
> +    stage_id = fields.Many2one('crm.stage', string='Stage', ondelete='restrict', track_visibility='onchange', index=True, copy=False,
cambia el dominio por eso lo volví a agregar. En lugar de team_id como estaba originalmente en el domain, debería usarse team_ids

2020-11-09 14:32 UTC, nmadhoc commented on crm_stage_teams/models/crm_lead.py
> +            search_domain = ['|', ('id', 'in', stages.ids), ('team_ids', '=', False)]
Lo había hecho siguiendo lo que estaba en crm_lead de v12
https://github.com/odoo/odoo/blob/34e5e8717f8fe428958ce7e7960713f44c34060f/addons/crm/models/crm_lead.py#L668
Avisame que te parece de hacer!

2020-11-24 12:14 UTC, nicomacr requested changes

2020-11-24 12:14 UTC, nicomacr commented on crm_stage_teams/README.rst
> +{module_title}
@nmadhoc completale con  el nombre del modulo aca

2020-11-24 12:14 UTC, nicomacr commented on crm_stage_teams/views/crm_stage_views.xml
> +        <!-- <record id="view_crm_case_opportunities_filter_inherit" model="ir.ui.view">
Por que esta comentado este registro de vista?

2020-11-24 12:15 UTC, nmadhoc commented on crm_stage_teams/views/crm_stage_views.xml
> +        <!-- <record id="view_crm_case_opportunities_filter_inherit" model="ir.ui.view">
porque me tiraba error al querer instalarlo y no pude encontrarle la solución. Al ser solo un agregado de un campo de búsqueda y no ser algo urgente opté por sacarlo para corroborar que funcione bien la instalación y pase las pruebas. Me olvidé de quitarlo, ahora lo hago!

2020-11-24 12:38 UTC, nicomacr submitted a review, later dismissed

2020-11-24 14:35 UTC, jjscarafia approved these changes

2020-11-24 17:51 UTC, merged