[13.0] [ADD] sale_gathering: Add new module sale_gathering
ingadhoc/sale pull request #432
Opened 2021-04-29 14:42 UTC by nicomacr

2021-06-07 20:49 UTC, jjscarafia requested changes
@nicomacr un par de pavadas..

2021-06-07 20:49 UTC, jjscarafia commented on sale_gathering/models/sale_order.py
> +    @api.depends('order_line', 'is_gathering')
entiendo que deberiamos cambiar el depends a:
```
    @api.depends(
        'is_gathering'
        'order_line.price_unit_with_tax',
        'order_line.qty_invoiced',
        'order_line.is_downpayment',
     )

```

2021-06-07 20:49 UTC, jjscarafia commented on sale_gathering/models/sale_order.py
> +    amount_gathering = fields.Float(
renombraría a  "Saldo Acopio" (gathering_balance)

2021-06-07 20:49 UTC, jjscarafia commented on sale_gathering/models/sale_order.py
> +                raise ValidationError(_("The amount gathering will be negative, you cannot add more products"
Dejaría así el mensaje

"The gathering balance will be negative (%s), you cannot make this modification to the order. Order: %s" % (rec.amount_gathering, rec.name)

2021-11-01 18:40 UTC, roboadhoc commented
Sorry, I didn't know about this PR and had to retrieve its information, you may have to re-approve it.

2021-11-01 18:41 UTC, roboadhoc commented
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/sale/pull/432).

2022-03-14 20:07 UTC, jjscarafia commented
@roboadhoc r+

2022-03-14 20:08 UTC, jjscarafia commented
@roboadhoc rebase-ff

2022-03-14 20:09 UTC, roboadhoc commented
Merge method set to rebase and fast-forward

2022-03-14 20:10 UTC, closed without merging