[FIX] portal_sale_distributor: Adjust to avoid bugs with other values in context
ingadhoc/sale pull request #492
Opened 2022-01-12 19:36 UTC by nicomacr

2022-01-12 19:37 UTC, roboadhoc commented
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/sale/pull/492).

2022-01-13 11:54 UTC, jjscarafia requested changes

2022-01-13 11:54 UTC, jjscarafia commented on portal_sale_distributor/models/ir_action_act_window.py
> +                ctx = safe_eval(value.get('context', '{}'))
cambiara por
                    eval_ctx = dict(self.env.context)
                    try:
                        ctx = safe_eval(values.get('context', '{}'), eval_ctx)
                    except:
                        ctx = {}

2022-01-13 11:54 UTC, jjscarafia commented on portal_sale_distributor/models/ir_action_act_window.py
> +                value.update({'context': ctx})
value.update({'context': str(ctx)})

2022-01-13 17:55 UTC, jjscarafia commented
@roboadhoc r+

2022-01-13 17:57 UTC, closed without merging