[MIG] sale_order_type_invoice_policy: Migration to 15.0
ingadhoc/sale pull request #554
Opened 2022-07-25 12:25 UTC by vib-adhoc

2022-07-25 12:26 UTC, roboadhoc commented
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/sale/pull/554).

2022-07-29 15:03 UTC, nicomacr requested changes
Hi Vir,
LGTM

2022-07-29 17:22 UTC, nicomacr approved these changes, later dismissed

2022-08-11 12:51 UTC, nicomacr commented
@roboadhoc r+

2022-08-11 12:54 UTC, closed without merging