Deleted force_company
ingadhoc/sale pull request #561
Opened 2022-08-05 18:48 UTC by JoelZilli

2022-08-05 18:49 UTC, roboadhoc commented
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/sale/pull/561).

2022-08-05 19:27 UTC, nicomacr requested changes

2022-08-05 19:27 UTC, nicomacr commented on sale_order_type_ux/models/sale_order.py
>                      self.partner_invoice_id.id, self.partner_shipping_id.id)
```suggestion
                    company.id).get_fiscal_position(self.partner_invoice_id.id)
```

2022-08-08 12:09 UTC, nicomacr commented
@roboadhoc r+

2022-08-08 12:11 UTC, closed without merging