[MIG] portal_sale_distributor: Migration to 15.0
ingadhoc/sale pull request #567
Opened 2022-08-26 18:43 UTC by JoelZilli

2022-08-26 18:44 UTC, roboadhoc commented
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/sale/pull/567).

2022-08-26 19:30 UTC, nicomacr requested changes

2022-08-26 19:30 UTC, nicomacr commented on portal_sale_distributor/views/product_template_views.xml
> +            </field> -->
@JoelZilli remove this comment lines

2022-08-30 12:36 UTC, JoelZilli commented on portal_sale_distributor/views/product_template_views.xml
> +            </field> -->
Done

2022-09-22 16:19 UTC, nicomacr commented
@roboadhoc r+

2022-09-22 20:20 UTC, nicomacr commented
@roboadhoc override=ci/oba_without_tests p=0

2022-09-22 20:21 UTC, nicomacr commented
@roboadhoc rebase-ff

2022-09-22 20:22 UTC, roboadhoc commented
Merge method set to rebase and fast-forward

2022-09-22 20:23 UTC, closed without merging