[FIX] sale_ux: update_prices fixed
ingadhoc/sale pull request #575
Opened 2022-09-19 19:48 UTC by vib-adhoc

2022-09-19 19:49 UTC, roboadhoc commented
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/sale/pull/575).

2022-09-21 18:50 UTC, nicomacr requested changes

2022-09-21 18:50 UTC, nicomacr commented on sale_ux/models/sale_order.py
> +            super(SaleOrder, self.with_context(lines_to_not_update_ids=products_pack.mapped('id'))).update_prices()
```suggestion
            super(SaleOrder, self.with_context(lines_to_not_update_ids=pack_lines.ids)).update_prices()
```

2022-09-21 18:50 UTC, nicomacr commented on sale_ux/models/sale_order.py
> +        return res
```suggestion
        lines = super()._get_update_prices_lines()
        lines_to_not_update_ids = self._context.get('lines_to_not_update_ids', [])
        return lines.filtered(lambda line: line.id not in lines_to_not_update_ids)
```

2022-09-21 18:50 UTC, nicomacr commented on sale_ux/models/sale_order.py
>              products_pack = self.order_line.with_context(update_prices=True, pricelist=self.pricelist_id.id).filtered(
```suggestion
            pack_lines = self.order_line.with_context(update_prices=True, pricelist=self.pricelist_id.id).filtered(
```

2022-09-21 18:50 UTC, nicomacr commented on sale_ux/models/sale_order.py
>              for line in products_pack:
```suggestion
            for line in pack_lines:
```

2022-09-22 20:31 UTC, nicomacr approved these changes

2022-09-22 20:31 UTC, nicomacr commented
@roboadhoc r+

2022-09-22 21:17 UTC, nicomacr commented
@roboadhoc override=ci/oba_without_tests p=0

2022-09-22 21:20 UTC, closed without merging