[ADD] timesheet so_line protections
ingadhoc/sale pull request #585
Opened 2022-10-24 20:06 UTC by jjscarafia

2022-10-24 20:06 UTC, roboadhoc commented
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/sale/pull/585).

2022-10-25 14:29 UTC, nicomacr requested changes

2022-10-25 14:29 UTC, nicomacr commented on sale_timesheet_ux/models/account_analytic_line.py
> +from odoo import models, fields
no se usa `fields`

2022-10-25 14:29 UTC, nicomacr commented on sale_timesheet_ux/__manifest__.py
>      ],
falta cambiar la version https://github.com/ingadhoc/sale/pull/585/files#diff-24037374e0934b65819fd5c43db8731e3cce334aff27143494ce0c9e60259d6dR4

2022-10-25 14:29 UTC, nicomacr commented on sale_timesheet_ux/README.rst
> +      3.1 en ticekts, si cambia: commercial partner, team_id.use_helpdesk_sale_timesheet, project_id.pricing_type o project_id.sale_line_id
```suggestion
   3. la linea de venta en tarea, ticket o proyecto asociados al parte de horas. Estos a su vez cambian si:
      3.1 en tickets, si cambia: commercial partner, team_id.use_helpdesk_sale_timesheet, project_id.pricing_type o project_id.sale_line_id
```

2022-10-25 19:39 UTC, jjscarafia commented
@roboadhoc r+

2022-10-25 19:57 UTC, jjscarafia commented
@roboadhoc override=ci/oba_without_tests

2022-10-25 19:57 UTC, jjscarafia commented
@roboadhoc rebase-ff

2022-10-25 19:57 UTC, roboadhoc commented
Merge method set to rebase and fast-forward.

2022-10-25 20:00 UTC, closed without merging