[MIG] sale_timesheet_ux: Migration to 16.0
ingadhoc/sale pull request #599
Opened 2022-12-02 18:09 UTC by matiasperalta1

2022-12-02 18:10 UTC, roboadhoc commented
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/sale/pull/599).

2022-12-29 17:57 UTC, JrAdhoc requested changes

2022-12-29 17:57 UTC, JrAdhoc commented on sale_timesheet_ux/models/project_task.py
> +    order_id = fields.Many2one('sale.order', 'Sales Order', store=True, help="Sales order to which the task is linked.")
@matiasperalta1 Mati, el build de runbot da un error que te dejo acá con este campo:
Two fields (order_id, sale_order_id) of project.task() have the same label: Sales Order. [Modules: sale_timesheet_ux and sale_timesheet]

2022-12-29 17:58 UTC, JrAdhoc commented
@matiasperalta1 
Tmb dice que hay que hacer un rebase a origin 16.0

2022-12-29 18:20 UTC, JrAdhoc commented
@roboadhoc r+

2022-12-29 18:55 UTC, JrAdhoc commented
@roboadhoc r+ override=ci/oba_without_tests p=0

2022-12-29 18:55 UTC, roboadhoc commented
I'm sorry, @JrAdhoc:
- this PR is already reviewed, reviewing it again is useless.
- you are not allowed to override this status.

2022-12-29 18:57 UTC, closed without merging