[MIG] sale_exception_credit_limit: Migration to 16.0
ingadhoc/sale pull request #621
Opened 2023-01-17 18:16 UTC by jok-adhoc

2023-01-17 18:17 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/621).

2023-01-27 17:23 UTC, nicomacr commented on sale_exception_credit_limit/models/res_partner.py
> +            # import pdb; pdb.set_trace()
borrar esta linea

2023-01-27 17:23 UTC, nicomacr commented on sale_exception_credit_limit/models/res_partner.py
> +        string='Total Receivable', help="Total amount this customer owes you (including not invoiced confirmed sale orders and draft invoices).",
cambiar label por otro nombre

2023-01-27 17:25 UTC, nicomacr commented on sale_exception_credit_limit/models/res_partner.py
> +            #         ('exclude_from_invoice_tab', '=', False),  VERIFICAR
es necesario? explayar un poco la razon

2023-01-27 17:26 UTC, nicomacr requested changes
check this point

2023-02-27 11:32 UTC, jok-adhoc commented on sale_exception_credit_limit/models/res_partner.py
> +            # import pdb; pdb.set_trace()
hecho

2023-02-27 11:33 UTC, jok-adhoc commented on sale_exception_credit_limit/models/res_partner.py
> +        string='Total Receivable', help="Total amount this customer owes you (including not invoiced confirmed sale orders and draft invoices).",
Acá habiamos hablado con Nico Col que les era buena opción que quede con el mismo label que el otro credit. Puede inducir algun error?

2023-02-27 11:34 UTC, jok-adhoc commented on sale_exception_credit_limit/models/res_partner.py
> +            #         ('exclude_from_invoice_tab', '=', False),  VERIFICAR
No existe mas el exclude_from_invoice_tab, verificamos sin el mismo el funcionamiento es el esperado

2023-02-27 11:39 UTC, nicomacr commented on sale_exception_credit_limit/models/res_partner.py
> +            #         ('exclude_from_invoice_tab', '=', False),  VERIFICAR
si no es conveniente que tengan el mismo nombre en el mismo modelo, odoo da una advertencia de esto, lo podes ver en el log de runbot

2023-02-27 11:39 UTC, nicomacr commented on sale_exception_credit_limit/models/res_partner.py
> +        string='Total Receivable', help="Total amount this customer owes you (including not invoiced confirmed sale orders and draft invoices).",
si no es conveniente que tengan el mismo nombre en el mismo modelo, odoo da una advertencia de esto, lo podes ver en el log de runbot

2023-02-27 11:40 UTC, jok-adhoc commented on sale_exception_credit_limit/models/res_partner.py
> +        string='Total Receivable', help="Total amount this customer owes you (including not invoiced confirmed sale orders and draft invoices).",
Perfecto! Lo veo con Nico Col este label

2023-02-27 16:22 UTC, jok-adhoc commented
@nicomacr nico, todo listo ya

2023-02-28 12:23 UTC, nicomacr commented
@roboadhoc rebase-ff r+

2023-02-28 12:24 UTC, roboadhoc commented
Merge method set to rebase and fast-forward.

2023-02-28 12:26 UTC, closed without merging