[FIX] use of user_id fixed
ingadhoc/sale pull request #642
Opened 2023-03-13 14:05 UTC by JoelZilli

2023-03-13 14:07 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/642).

2023-03-13 15:23 UTC, nicomacr requested changes
@JoelZilli please check this comment below

2023-03-13 15:23 UTC, nicomacr commented on crm_teams_ux/views/crm_lead_views.xml
> +        </field>
```suggestion
            <xpath expr="//field[@name='user_id'][1] position="attributes">
                <attribute name="domain">[('company_ids', 'in', user_company_ids)]</attribute>
                <attribute name="groups">sale_ux.group_allow_any_user_as_salesman</attribute>
            </field>
            <xpath expr="//field[@name='user_id'][2] position="attributes">
                <attribute name="domain">[('company_ids', 'in', user_company_ids)]</attribute>
                <attribute name="groups">sale_ux.group_allow_any_user_as_salesman</attribute>
            </field>
            <xpath expr="//field[@name='user_id'][1] position="after">
                <field name="user_id" groups="!sale_ux.group_allow_any_user_as_salesman" context="{'default_sales_team_id': team_id}" widget="many2one_avatar_user"/>
            </field>
            <xpath expr="//field[@name='user_id'][2] position="after">
                <field name="user_id" groups="!sale_ux.group_allow_any_user_as_salesman" context="{'default_sales_team_id': team_id}" widget="many2one_avatar_user"/>
            </field>
        </field>
```

2023-03-16 16:01 UTC, nicomacr commented
@roboadhoc r+

2023-03-16 16:07 UTC, closed without merging