[MIG] sale_order_type_invoice_policy: Migration to 17.0
ingadhoc/sale pull request #763
Opened 2023-12-27 17:31 UTC by ALopez-Adhoc

2023-12-27 17:32 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/763).

2024-05-24 14:12 UTC, matiasperalta1 requested changes

2024-05-24 14:12 UTC, matiasperalta1 commented on sale_order_type_invoice_policy/demo/sale_order_demo.xml
> +        <!-- <field name="pricelist_id" ref="product.list0"/> -->
Cambio el id de la pricelist? O simplemente desapareció? Igualmente borralo si no va

2024-05-28 15:35 UTC, ALopez-Adhoc commented on sale_order_type_invoice_policy/demo/sale_order_demo.xml
> +        <!-- <field name="pricelist_id" ref="product.list0"/> -->
Hice un rastreo y no lo encontre, en el unico otro lugar que lo usabamos (ahora no recuerdo que vista demo era) fue borrado, por eso me incline por sacarlo y funciona con normalidad. Ya esta borrado.

2024-05-29 13:17 UTC, matiasperalta1 commented
@roboadhoc r+

2024-05-29 13:20 UTC, closed without merging