[IMP] sale_gathering and [ADD] sale_gathering_index
ingadhoc/sale pull request #767
Opened 2024-01-03 16:49 UTC by lef-adhoc

2024-01-03 16:49 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/767).

2024-04-11 19:59 UTC, jjscarafia requested changes

2024-04-11 19:59 UTC, jjscarafia commented on sale_gathering/models/sale_order.py
> +    amount = fields.Float(compute="_compute_amount", help='Monto, sin impuestos, acopiado inicialmente.')
si es un amount que solo tiene sentido dentro de la lógica gathering lo llamaría "gathering_amount" o algo así, de hecho creo que el string automático tmb tendría sentido "Gathering Amount"

2024-04-11 19:59 UTC, jjscarafia commented on sale_gathering/models/sale_order.py
> +        orders = self.search([('is_gathering', '=', True)]).filtered(lambda x: x.gathering_balance > 0.0)
jejeje este es un hack medio feo que a la larga no va a ir bien. A medida que crezca la base va a ser un filtered sobre cada vez más ordenes de venta para poder obtener este resultado. (más info en video que comparto en sistemas para complementar capacitación de hoy)

si el resto de los campos que se usan para computar el "gathering_balance" son almacenados tal vez no esté tan mal pensar en hacerlo almacenado y listo.. (si el depends no se vuelve super loco)

2024-04-11 19:59 UTC, jjscarafia commented on sale_gathering/models/sale_order.py
> +                    [self.env['account.tax']._convert_to_tax_base_line_dict(
hace fala esto de convert_Tax_tabase_line_dict? no se puede algo más simple simil esto? https://github.com/odoo/odoo/blob/16.0/addons/sale/models/sale_order_line.py#L883

2024-04-11 19:59 UTC, jjscarafia commented on sale_gathering_index/models/sale_order.py
> +                    [self.env['account.tax']._convert_to_tax_base_line_dict(
idem casos arriba, me suea que todo este código debería poder ser más simple

2024-04-11 19:59 UTC, jjscarafia commented on sale_gathering_index/models/sale_order_line.py
> +    def create(self, vals_list):
no profundicé, pero me hacen un poco de ruido conceptual estas extensiones de create y write

2024-04-16 20:59 UTC, lef-adhoc commented on sale_gathering/models/sale_order.py
> +                    [self.env['account.tax']._convert_to_tax_base_line_dict(
Lo saqué de acá si no me equivoco: https://github.com/odoo/odoo/blob/71bd27465b83732be0a25aa14c249cf8ba2e2468/addons/sale/models/sale_order_line.py#L621C72-L621C102

Tuve que hacerlo más largo yo ya que el diccionario es distinto del de ese método por esto: https://github.com/odoo/odoo/blob/71bd27465b83732be0a25aa14c249cf8ba2e2468/addons/sale/models/sale_order_line.py#L610
Y en el mío debería ser: quantity=line.initial_qty_gathered

2024-04-16 21:01 UTC, lef-adhoc commented on sale_gathering/models/sale_order.py
> +        orders = self.search([('is_gathering', '=', True)]).filtered(lambda x: x.gathering_balance > 0.0)
Perfecto lo dejo como almacenado !

2024-04-22 09:25 UTC, jjscarafia requested changes

2024-04-22 09:25 UTC, jjscarafia commented on sale_gathering/models/sale_order.py
> +    @api.depends('is_gathering', 'invoice_ids')
@api.depends('is_gathering', 'invoice_ids.state')

2024-04-22 09:25 UTC, jjscarafia commented on sale_gathering/models/sale_order_line.py
> +    def _compute_price_unit(self):
pondria depends a "initial_qty_gathered"
tal vez tmb a "order_id.is_gathering"

2024-04-22 18:59 UTC, matiasperalta1 requested changes

2024-04-22 18:59 UTC, matiasperalta1 commented on sale_gathering/models/sale_order_line.py
> +from odoo import models, fields
importar api ya uqe despues e usa mas abajo en api.depends

2024-04-22 19:28 UTC, matiasperalta1 commented
@roboadhoc r+ rebase-ff

2024-04-22 19:29 UTC, roboadhoc commented
Merge method set to rebase and fast-forward.

2024-04-22 19:31 UTC, closed without merging