[IMP]sale_timesheet_ux: mantain relation between task and SO
ingadhoc/sale pull request #785
Opened 2024-02-15 16:23 UTC by ALopez-Adhoc

2024-02-15 16:24 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/785).

2024-02-19 11:37 UTC, jok-adhoc commented on sale_timesheet_ux/models/project_task.py
> +        # between the task with the SO that originated it
Me parece bien la idea, ahora.. está contemplado qué pasa si se actualiza algo en el metodo que se copia?

Para evitar quedar desfasado tal vez se puede llamar al super antes seteando para todo el self el allow_billable y despues de ejecutar el super volverlo para atrás. Entonces, si hay un cambio en sale_project lo va a tomar siempre, solo que con esto va a evitar lo de sale_timesheet

La idea de restaurarlo la usamos acá: https://github.com/ingadhoc/enterprise-extensions/blob/17.0/sale_subscription_ux/models/sale_order.py#L93 

Desconozco si esto funcionaria bien y si hay otros métodos que pueden llegar a afectar (viendo las herencias creeria que no), pero lo que lo hace es más sustentable a un cambio en lo nativo

2024-02-19 19:18 UTC, jok-adhoc requested changes

2024-02-19 19:18 UTC, jok-adhoc commented on sale_timesheet_ux/models/project_task.py
> +
borrar linea

2024-02-19 19:18 UTC, jok-adhoc commented on sale_timesheet_ux/models/project_task.py
> +
borrar linea

2024-02-19 19:18 UTC, jok-adhoc commented on sale_timesheet_ux/models/project_task.py
> +
borrar linea

2024-02-19 19:33 UTC, jok-adhoc commented
@roboadhoc r+

2024-02-19 19:43 UTC, closed without merging