[IMP] portal_sale_distributor: show only sale pr..
ingadhoc/sale pull request #788
Opened 2024-02-20 21:20 UTC by ica-adhoc

..oducts in Catalog

2024-02-20 21:21 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/788).

2024-03-05 20:31 UTC, jjscarafia commented
@roboadhoc r+

2024-03-05 20:31 UTC, jjscarafia commented
@roboadhoc r-

2024-03-12 20:38 UTC, jjscarafia requested changes
Iría por approach de rules

2024-03-20 11:53 UTC, jjscarafia commented
@roboadhoc r+

2024-03-20 11:54 UTC, jjscarafia commented
@roboadhoc r-

2024-04-30 00:27 UTC, jjscarafia commented
cerramos ya que rompe cosas, como por ejemplo, agregar carriers en una venta de portal

2024-04-30 00:27 UTC, closed without merging