[IMP] new module pos_ux
ingadhoc/sale pull request #825
Opened 2024-05-10 23:50 UTC by maq-adhoc

2024-05-10 23:51 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/825).

2024-05-28 17:14 UTC, lef-adhoc approved these changes

2024-06-04 16:15 UTC, matiasperalta1 requested changes

2024-06-04 16:15 UTC, matiasperalta1 commented on pos_ux/__manifest__.py
> +    'version': '1.0',
La version es correcta o debería ser 16.0.1.0.0 ?

2024-06-04 16:15 UTC, matiasperalta1 commented on pos_ux/models/pos_config.py
> +# -*- coding: utf-8 -*-
Se puede eliminar este comentario

2024-06-04 16:15 UTC, matiasperalta1 commented on pos_ux/models/pos_order.py
> +# -*- coding: utf-8 -*-
eliminar comentario

2024-06-04 16:15 UTC, matiasperalta1 commented on pos_ux/models/pos_session.py
> +# -*- coding: utf-8 -*-
eliminar comentarios

2024-06-04 16:15 UTC, matiasperalta1 commented on pos_ux/views/pos_session_view.xml
> +</odoo>
borrar ultima linea sin uso, lo mismo para res_config_Settings_views.xml

2024-06-04 16:15 UTC, matiasperalta1 commented on pos_ux/__manifest__.py
> +    'auto_install': True,
Creo aca en auto_install se pone como falso y despues desde los adhoc modules de nuestra base elegir mejor opción en "Auto Installation Policy"

2024-08-06 12:52 UTC, matiasperalta1 commented
@roboadhoc r+

2024-08-06 13:17 UTC, roboadhoc commented
@maq-adhoc @matiasperalta1 linked pull request(s) ingadhoc/odoo-argentina#845 not ready. Linked PRs are not staged until all of them are ready.

2024-08-08 14:07 UTC, closed without merging