IMP portal sale distributor
ingadhoc/sale pull request #97
Opened 2018-03-08 14:14 UTC by nicomacr

2018-03-08 22:30 UTC, jjscarafia requested changes
También ver el error de runbot, parece que hay reglas de más que no son necesarias (o falta dependencia a un módulo) http://runbot.adhoc.com.ar/runbot/static/build/01947-97-c16031/logs/job_20_test_all.txt

2018-03-08 22:30 UTC, jjscarafia commented on portal_sale_distributor/models/product.py
> +    standard_price = fields.Float(
Esto es necesario nico? porque necesita permiso para este campo? Está en la vista? no lo podemos sacar?

2018-03-08 22:30 UTC, jjscarafia commented on portal_sale_distributor/__openerp__.py
> +    'auto_install': True,
No hacer auto-instalable. poner false

2018-03-09 12:36 UTC, nicomacr commented
se cambio por este https://github.com/ingadhoc/enterprise-extensions/pull/24

2018-03-09 15:16 UTC, closed without merging