[MIG] portal_sale_distributor: Migration to 18.0
ingadhoc/sale pull request #983
Opened 2024-10-21 13:18 UTC by lav-adhoc

2024-10-21 13:19 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/sale/pull/983).

2024-11-14 14:53 UTC, nicolascol commented
@roboadhoc r+

2024-11-14 14:54 UTC, roboadhoc commented
I'm sorry, @nicolascol. I'm afraid I can't do that.

2024-11-14 14:59 UTC, matiasperalta1 requested changes

2024-11-14 14:59 UTC, matiasperalta1 commented on portal_sale_distributor/models/partner.py
> +        groups='account.group_account_invoice,account.group_account_readonly,portal_sale_distributor.group_portal_backend_distributor')
borrar ese enter

2024-11-14 14:59 UTC, matiasperalta1 commented on portal_sale_distributor/models/partner.py
> +        groups='account.group_account_invoice,account.group_account_readonly,portal_sale_distributor.group_portal_backend_distributor')
e identar

2024-11-14 15:43 UTC, matiasperalta1 commented
@roboadhoc r+

2024-11-14 15:47 UTC, closed without merging